pub mod departures_parser;
#[cfg(feature = "geoclue")]
pub mod geoclue;
#[cfg(target_os = "android")]
pub mod jni_utils;
pub mod preferences;
pub mod routes_parser;
pub mod stops_parser;
pub mod text_utils;
